# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('national', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('pub_type', models.CharField(choices=[('1', 'Journal'), ('2', 'Confrance'), ('3', 'Book')], max_length=10)),
                ('details', models.CharField(max_length=500)),
                ('identifier', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='research_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.ResearchField'),
        ),
    ]
