# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20171126_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
