# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publication_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
